quiz = [{'category': 'history',
      'correctAnswer': 'Abraham Lincoln',
      'difficulty': 'medium',
      'id': '63a039cac7d86251f9b65cb5',
      'incorrectAnswers': ['John Adams', 'Thomas Jefferson', 'Andrew Johnson'],
      'isNiche': 'False',
      'question': {'text': 'Which president signed the Emancipation Proclamation?'},
      'regions': [],
      'tags': ['history', 'usa', 'presidents'],
      'type': 'text_choice'},
     {'category': 'food_and_drink',
      'correctAnswer': 'Guinness',
      'difficulty': 'easy',
      'id': '622a1c367cc59eab6f95022f',
      'incorrectAnswers': ['Porters', 'Doogals', 'Old Black'],
      'isNiche': 'False',
      'question': {'text': 'Which stout is Dublin world-famous for?'},
      'regions': [],
      'tags': ['food_and_drink'],
      'type': 'text_choice'},
     {'category': 'arts_and_literature',
      'correctAnswer': 'Franz Kafka',
      'difficulty': 'hard',
      'id': '622a1c397cc59eab6f950e9b',
      'incorrectAnswers': ['Émile Zola', 'Nathaniel Hawthorne', 'Leo Tolstoy'],
      'isNiche': 'False',
      'question': {'text': "Which author wrote 'The Metamorphosis'?"},
      'regions': [],
      'tags': ['arts_and_literature'],
      'type': 'text_choice'},
     {'category': 'music',
      'correctAnswer': 'Lady Gaga',
      'difficulty': 'easy',
      'id': '622a1c357cc59eab6f94fe7f',
      'incorrectAnswers': ['Hikaru Utada', 'Drake', 'Madonna'],
      'isNiche': 'False',
      'question': {'text': 'Which American singer, songwriter, and actress '
                           "released the song 'Bad Romance'?"},
      'regions': [],
      'tags': ['general_knowledge', 'music'],
      'type': 'text_choice'},
     {'category': 'science',
      'correctAnswer': 'Antennae',
      'difficulty': 'medium',
      'id': '645ba87ff09106226db23582',
      'incorrectAnswers': ['Ears', 'Noses', 'Tongues'],
      'isNiche': 'False',
      'question': {'text': 'What do most butterflies use to smell?'},
      'regions': [],
      'tags': ['biology', 'insects', 'science', 'animals'],
      'type': 'text_choice'},
     {'category': 'society_and_culture',
      'correctAnswer': 'Six',
      'difficulty': 'medium',
      'id': '6266e679ff2394bd44dee04d',
      'incorrectAnswers': ['Seven', 'Yellow', 'Two'],
      'isNiche': 'False',
      'question': {'text': "What does the word 'seis' mean in Spanish?"},
      'regions': [],
      'tags': ['language', 'translations', 'society_and_culture'],
      'type': 'text_choice'},
     {'category': 'general_knowledge',
      'correctAnswer': 'Ill-willie',
      'difficulty': 'hard',
      'id': '622a1c357cc59eab6f94fc74',
      'incorrectAnswers': ['Fipple', 'Oxter', 'Octothorpe'],
      'isNiche': 'False',
      'question': {'text': "Which word is defined as 'having an unfriendly "
                           "disposition'?"},
      'regions': [],
      'tags': ['words', 'general_knowledge'],
      'type': 'text_choice'},
     {'category': 'music',
      'correctAnswer': 'Black Sabbath',
      'difficulty': 'hard',
      'id': '622a1c397cc59eab6f950be5',
      'incorrectAnswers': ['Skunk Anansie', 'Kasabian', 'Emerson, Lake & Palmer'],
      'isNiche': 'False',
      'question': {'text': 'Which British heavy metal band released the studio '
                           "album 'Paranoid'?"},
      'regions': [],
      'tags': ['music'],
      'type': 'text_choice'},
     {'category': 'society_and_culture',
      'correctAnswer': 'Forseti',
      'difficulty': 'hard',
      'id': '622a1c367cc59eab6f9500f4',
      'incorrectAnswers': ['Baldur', 'Thor', 'Odin'],
      'isNiche': 'False',
      'question': {'text': 'Who is the Norse god of justice?'},
      'regions': [],
      'tags': ['society_and_culture'],
      'type': 'text_choice'},
     {'category': 'society_and_culture',
      'correctAnswer': 'Amor vincit omnia',
      'difficulty': 'medium',
      'id': '6371621d1bf863c45ca6c353',
      'incorrectAnswers': ['Fortiter et fideliter', 'Memento vivere', 'Sic infit'],
      'isNiche': 'False',
      'question': {'text': "Which of these Latin phrases means 'Love conquers "
                           "all'?"},
      'regions': [],
      'tags': ['society_and_culture', 'language', 'the_romans', 'classics'],
      'type': 'text_choice'}]

